Fix variable scope on TF 0.12
ValueError: Variable b1/Adam/ does not exist, or was not created with
tf.get_variable(). Did you mean to set reuse=None in VarScope?